export enum WAS_EVENT_TYPE {
  TALK = "TALK",
  BATTLE = "BATTLE",
  PLAY_AUDIO = "PLAY_AUDIO",
  LEARN_SKILL = "LEARN_SKILL",
  UPDATE_ALLY = "UPDATE_ALLY",
  UPDATE_STATE = "UPDATE_STATE",
  CHANGE_PAGE = "CHANGE_PAGE",
}

export enum WAS_EVENT_STATE_TYPE {
  GAME_CLEAR = "GAME_CLEAR",
  CHAPTER = "CHAPTER",
  AREA_INVADED = "AREA_INVADED",
  AREA_MANAGED = "AREA_MANAGED",
  CHARACTER_FRIENDLY = "CHARACTER_FRIENDLY",
  CHARACTER_ALIVE = "CHARACTER_ALIVE",
}

export enum WAS_EVENT_CONDITION_TYPE {
  ALIVE = "ALIVE",
  FRIENDLY = "FRIENDLY",
  INVADE = "INVADE",
  MANAGE = "MANAGE",
  CHAPTER = "CHAPTER",
}

export enum WAS_STATE_CONDITION {
  SLEEP = "SLEEP",
  POISON = "POISON",
  ACTIVITY = "ACTIVITY",
  AWAKING_HERO = "AWAKING_HERO",
  AWAKING_SATAN = "AWAKING_SATAN",
  ATTACK_UP = "ATTACK_UP",
  DEFENCE_UP = "DEFENCE_UP",
  SPEED_UP = "SPEED_UP",
  ATTACK_DOWN = "ATTACK_DOWN",
  DEFENCE_DOWN = "DEFENCE_DOWN",
  SPEED_DOWN = "SPEED_DOWN",
  DOWBLE_MOVE = "DOWBLE_MOVE",
  ANY_MOVE = "ANY_MOVE",
}

export enum WAS_SKILL_TYPE {
  CONST_DAMAGE = "CONST_DAMAGE",
  ATTACK_VS_DEFFECE_DAMAGE = "ATTACK_VS_DEFFECE_DAMAGE",
  CONST_HEAL = "CONST_HEAL",
  RATE_HEAL = "RATE_HEAL",
  GRANT_STATE_CONDITION = "GRANT_STATE_CONDITION",
  RELEASE_STATE_CONDITION = "RELEASE_STATE_CONDITION",
}
