export enum WAS_STATE_CONDITION {
  SLEEP = "SLEEP",
  POISON = "POISON",
  ACTIVITY = "ACTIVITY",
  AWAKING_HERO = "AWAKING_HERO",
  AWAKING_SATAN = "AWAKING_SATAN",
  ATTACK_UP = "ATTACK_UP",
  DEFENCE_UP = "DEFENCE_UP",
  SPEED_UP = "SPEED_UP",
  ATTACK_DOWN = "ATTACK_DOWN",
  DEFENCE_DOWN = "DEFENCE_DOWN",
  SPEED_DOWN = "SPEED_DOWN",
  DOWBLE_MOVE = "DOWBLE_MOVE",
  ANY_MOVE = "ANY_MOVE",
}

export enum WAS_SKILL_TYPE {
  CONST_DAMAGE = "CONST_DAMAGE",
  ATTACK_VS_DEFFECE_DAMAGE = "ATTACK_VS_DEFFECE_DAMAGE",
  CONST_HEAL = "CONST_HEAL",
  RATE_HEAL = "RATE_HEAL",
  GRANT_STATE_CONDITION = "GRANT_STATE_CONDITION",
  RELEASE_STATE_CONDITION = "RELEASE_STATE_CONDITION",
}
