export enum WAS_EVENT_TYPE {
  TALK = "TALK",
  BATTLE = "BATTLE",
  PLAY_AUDIO = "PLAY_AUDIO",
  LEARN_SKILL = "LEARN_SKILL",
  UPDATE_ALLY = "UPDATE_ALLY",
  UPDATE_STATE = "UPDATE_STATE",
  CHANGE_PAGE = "CHANGE_PAGE",
}

export enum WAS_EVENT_STATE_TYPE {
  GAME_CLEAR = "GAME_CLEAR",
  CHAPTER = "CHAPTER",
  AREA = "AREA",
  CHARACTER = "CHARACTER",
}

export enum WAS_EVENT_CONDITION_TYPE {
  GAME_CLEAR = "GAME_CLEAR",
  AREA = "AREA",
  CHARACTER = "CHARACTER",
  CHAPTER = "CHAPTER",
  ACCOMPANY = "ACCOMPANY",
}

export enum WAS_AREA_STATE_TYPE {
  HIDDEN = "HIDDEN",
  OPENED = "OPENED",
}

export enum WAS_CHARACTER_STATE_TYPE {
  NEUTRAL = "NEUTRAL",
  ANGRY = "ANGRY",
  FRIENDLY = "FRIENDLY",
  ALIVE = "ALIVE",
  DEAD = "DEAD",
}

export enum WAS_STATE_CONDITION {
  SLEEP = "SLEEP",
  POISON = "POISON",
  ACTIVITY = "ACTIVITY",
  AWAKING_HERO = "AWAKING_HERO",
  AWAKING_SATAN = "AWAKING_SATAN",
  ATTACK_UP = "ATTACK_UP",
  DEFENSE_UP = "DEFENSE_UP",
  SPEED_UP = "SPEED_UP",
  ATTACK_DOWN = "ATTACK_DOWN",
  DEFENSE_DOWN = "DEFENSE_DOWN",
  SPEED_DOWN = "SPEED_DOWN",
  DOWBLE_MOVE = "DOWBLE_MOVE",
  ANY_MOVE = "ANY_MOVE",
}

export enum WAS_SKILL_TYPE {
  DAMAGE = "DAMAGE",
  HEAL = "HEAL",
  GRANT_STATE_CONDITION = "GRANT_STATE_CONDITION",
  RELEASE_STATE_CONDITION = "RELEASE_STATE_CONDITION",
  MESSAGE = "MESSAGE"
}

export enum WAS_OPERATOR {
  EQUAL = "eq",
  GREATER_THAN_EQUAL = "ge",
  LESS_THAN_EQUALL = "le",
  GREATER_THAN = "gt",
  LESS_THAN = "lt",
}
